### ISSUE TITLE
Space separated list of available widths

### ISSUE THREAD

**Issue by sindresorhus** [addyosmani/x-imager#1]
I think a space separated list would be more natural HTML than an array:

``` html
<x-imager availableWidths="[400, 460, 420, 1200]">
```

to

``` html
<x-imager available-widths="400 460 420 1200">
```

Also no camelCase.

**Comment by addyosmani** [comment]
Thanks for the feedback. In this case I opted for an array to match the original Imager API, but space-separated would be cleaner. I'll update to support it.

The move away from camelCase also sgtm.

**Comment by sindresorhus** [comment]
I would probably also shorten the attribute to just `widths`

**Comment by addyosmani** [comment]
Done.
